//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalNetworkDevice)(nil), (*v1alpha2.AdditionalNetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(a.(*AdditionalNetworkDevice), b.(*v1alpha2.AdditionalNetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AdditionalNetworkDevice)(nil), (*AdditionalNetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(a.(*v1alpha2.AdditionalNetworkDevice), b.(*AdditionalNetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiskSize)(nil), (*v1alpha2.DiskSize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(a.(*DiskSize), b.(*v1alpha2.DiskSize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DiskSize)(nil), (*DiskSize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(a.(*v1alpha2.DiskSize), b.(*DiskSize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPAddress)(nil), (*v1alpha2.IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(a.(*IPAddress), b.(*v1alpha2.IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.IPAddress)(nil), (*IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(a.(*v1alpha2.IPAddress), b.(*IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPConfigSpec)(nil), (*v1alpha2.IPConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(a.(*IPConfigSpec), b.(*v1alpha2.IPConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.IPConfigSpec)(nil), (*IPConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(a.(*v1alpha2.IPConfigSpec), b.(*IPConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InterfaceConfig)(nil), (*v1alpha2.InterfaceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(a.(*InterfaceConfig), b.(*v1alpha2.InterfaceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InterfaceConfig)(nil), (*InterfaceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(a.(*v1alpha2.InterfaceConfig), b.(*InterfaceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetadataSettings)(nil), (*v1alpha2.MetadataSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(a.(*MetadataSettings), b.(*v1alpha2.MetadataSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.MetadataSettings)(nil), (*MetadataSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(a.(*v1alpha2.MetadataSettings), b.(*MetadataSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkDevice)(nil), (*v1alpha2.NetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(a.(*NetworkDevice), b.(*v1alpha2.NetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NetworkDevice)(nil), (*NetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(a.(*v1alpha2.NetworkDevice), b.(*NetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1alpha2.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha2.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(a.(*v1alpha2.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*v1alpha2.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(a.(*NetworkStatus), b.(*v1alpha2.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*v1alpha2.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocation)(nil), (*v1alpha2.NodeLocation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(a.(*NodeLocation), b.(*v1alpha2.NodeLocation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NodeLocation)(nil), (*NodeLocation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(a.(*v1alpha2.NodeLocation), b.(*NodeLocation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocations)(nil), (*v1alpha2.NodeLocations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(a.(*NodeLocations), b.(*v1alpha2.NodeLocations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NodeLocations)(nil), (*NodeLocations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(a.(*v1alpha2.NodeLocations), b.(*NodeLocations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxCluster)(nil), (*v1alpha2.ProxmoxCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(a.(*ProxmoxCluster), b.(*v1alpha2.ProxmoxCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxCluster)(nil), (*ProxmoxCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(a.(*v1alpha2.ProxmoxCluster), b.(*ProxmoxCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterCloneSpec)(nil), (*v1alpha2.ProxmoxClusterCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(a.(*ProxmoxClusterCloneSpec), b.(*v1alpha2.ProxmoxClusterCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterCloneSpec)(nil), (*ProxmoxClusterCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(a.(*v1alpha2.ProxmoxClusterCloneSpec), b.(*ProxmoxClusterCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterList)(nil), (*v1alpha2.ProxmoxClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(a.(*ProxmoxClusterList), b.(*v1alpha2.ProxmoxClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterList)(nil), (*ProxmoxClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(a.(*v1alpha2.ProxmoxClusterList), b.(*ProxmoxClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterSpec)(nil), (*v1alpha2.ProxmoxClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(a.(*ProxmoxClusterSpec), b.(*v1alpha2.ProxmoxClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterStatus)(nil), (*v1alpha2.ProxmoxClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(a.(*ProxmoxClusterStatus), b.(*v1alpha2.ProxmoxClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterStatus)(nil), (*ProxmoxClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(a.(*v1alpha2.ProxmoxClusterStatus), b.(*ProxmoxClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplate)(nil), (*v1alpha2.ProxmoxClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(a.(*ProxmoxClusterTemplate), b.(*v1alpha2.ProxmoxClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplate)(nil), (*ProxmoxClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(a.(*v1alpha2.ProxmoxClusterTemplate), b.(*ProxmoxClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplateList)(nil), (*v1alpha2.ProxmoxClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(a.(*ProxmoxClusterTemplateList), b.(*v1alpha2.ProxmoxClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplateList)(nil), (*ProxmoxClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(a.(*v1alpha2.ProxmoxClusterTemplateList), b.(*ProxmoxClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplateResource)(nil), (*v1alpha2.ProxmoxClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(a.(*ProxmoxClusterTemplateResource), b.(*v1alpha2.ProxmoxClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplateResource)(nil), (*ProxmoxClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(a.(*v1alpha2.ProxmoxClusterTemplateResource), b.(*ProxmoxClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplateSpec)(nil), (*v1alpha2.ProxmoxClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(a.(*ProxmoxClusterTemplateSpec), b.(*v1alpha2.ProxmoxClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplateSpec)(nil), (*ProxmoxClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(a.(*v1alpha2.ProxmoxClusterTemplateSpec), b.(*ProxmoxClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachine)(nil), (*v1alpha2.ProxmoxMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(a.(*ProxmoxMachine), b.(*v1alpha2.ProxmoxMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachine)(nil), (*ProxmoxMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(a.(*v1alpha2.ProxmoxMachine), b.(*ProxmoxMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineChecks)(nil), (*v1alpha2.ProxmoxMachineChecks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(a.(*ProxmoxMachineChecks), b.(*v1alpha2.ProxmoxMachineChecks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineChecks)(nil), (*ProxmoxMachineChecks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(a.(*v1alpha2.ProxmoxMachineChecks), b.(*ProxmoxMachineChecks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineList)(nil), (*v1alpha2.ProxmoxMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(a.(*ProxmoxMachineList), b.(*v1alpha2.ProxmoxMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineList)(nil), (*ProxmoxMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(a.(*v1alpha2.ProxmoxMachineList), b.(*ProxmoxMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineSpec)(nil), (*v1alpha2.ProxmoxMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(a.(*ProxmoxMachineSpec), b.(*v1alpha2.ProxmoxMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineSpec)(nil), (*ProxmoxMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(a.(*v1alpha2.ProxmoxMachineSpec), b.(*ProxmoxMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineStatus)(nil), (*v1alpha2.ProxmoxMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(a.(*ProxmoxMachineStatus), b.(*v1alpha2.ProxmoxMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineStatus)(nil), (*ProxmoxMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(a.(*v1alpha2.ProxmoxMachineStatus), b.(*ProxmoxMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplate)(nil), (*v1alpha2.ProxmoxMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(a.(*ProxmoxMachineTemplate), b.(*v1alpha2.ProxmoxMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplate)(nil), (*ProxmoxMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(a.(*v1alpha2.ProxmoxMachineTemplate), b.(*ProxmoxMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateList)(nil), (*v1alpha2.ProxmoxMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(a.(*ProxmoxMachineTemplateList), b.(*v1alpha2.ProxmoxMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateList)(nil), (*ProxmoxMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(a.(*v1alpha2.ProxmoxMachineTemplateList), b.(*ProxmoxMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateResource)(nil), (*v1alpha2.ProxmoxMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(a.(*ProxmoxMachineTemplateResource), b.(*v1alpha2.ProxmoxMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateResource)(nil), (*ProxmoxMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(a.(*v1alpha2.ProxmoxMachineTemplateResource), b.(*ProxmoxMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateSpec)(nil), (*v1alpha2.ProxmoxMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(a.(*ProxmoxMachineTemplateSpec), b.(*v1alpha2.ProxmoxMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateSpec)(nil), (*ProxmoxMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(a.(*v1alpha2.ProxmoxMachineTemplateSpec), b.(*ProxmoxMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteSpec)(nil), (*v1alpha2.RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(a.(*RouteSpec), b.(*v1alpha2.RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RouteSpec)(nil), (*RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(a.(*v1alpha2.RouteSpec), b.(*RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Routing)(nil), (*v1alpha2.Routing)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Routing_To_v1alpha2_Routing(a.(*Routing), b.(*v1alpha2.Routing), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Routing)(nil), (*Routing)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Routing_To_v1alpha1_Routing(a.(*v1alpha2.Routing), b.(*Routing), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoutingPolicySpec)(nil), (*v1alpha2.RoutingPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(a.(*RoutingPolicySpec), b.(*v1alpha2.RoutingPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.RoutingPolicySpec)(nil), (*RoutingPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(a.(*v1alpha2.RoutingPolicySpec), b.(*RoutingPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SchedulerHints)(nil), (*v1alpha2.SchedulerHints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(a.(*SchedulerHints), b.(*v1alpha2.SchedulerHints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.SchedulerHints)(nil), (*SchedulerHints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(a.(*v1alpha2.SchedulerHints), b.(*SchedulerHints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*v1alpha2.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_v1alpha2_Storage(a.(*Storage), b.(*v1alpha2.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Storage_To_v1alpha1_Storage(a.(*v1alpha2.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VMIDRange)(nil), (*v1alpha2.VMIDRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(a.(*VMIDRange), b.(*v1alpha2.VMIDRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VMIDRange)(nil), (*VMIDRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(a.(*v1alpha2.VMIDRange), b.(*VMIDRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VRFDevice)(nil), (*v1alpha2.VRFDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(a.(*VRFDevice), b.(*v1alpha2.VRFDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VRFDevice)(nil), (*VRFDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(a.(*v1alpha2.VRFDevice), b.(*VRFDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*v1alpha2.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(a.(*VirtualMachine), b.(*v1alpha2.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(a.(*v1alpha2.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineCloneSpec)(nil), (*v1alpha2.VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(a.(*VirtualMachineCloneSpec), b.(*v1alpha2.VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualMachineCloneSpec)(nil), (*VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(a.(*v1alpha2.VirtualMachineCloneSpec), b.(*VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualNetworkDevices)(nil), (*v1alpha2.VirtualNetworkDevices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(a.(*VirtualNetworkDevices), b.(*v1alpha2.VirtualNetworkDevices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualNetworkDevices)(nil), (*VirtualNetworkDevices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(a.(*v1alpha2.VirtualNetworkDevices), b.(*VirtualNetworkDevices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxClusterSpec)(nil), (*ProxmoxClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(a.(*v1alpha2.ProxmoxClusterSpec), b.(*ProxmoxClusterSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(in *AdditionalNetworkDevice, out *v1alpha2.AdditionalNetworkDevice, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(&in.NetworkDevice, &out.NetworkDevice, s); err != nil {
		return err
	}
	out.Name = in.Name
	if err := Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(&in.InterfaceConfig, &out.InterfaceConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice is an autogenerated conversion function.
func Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(in *AdditionalNetworkDevice, out *v1alpha2.AdditionalNetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(in, out, s)
}

func autoConvert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(in *v1alpha2.AdditionalNetworkDevice, out *AdditionalNetworkDevice, s conversion.Scope) error {
	if err := Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(&in.NetworkDevice, &out.NetworkDevice, s); err != nil {
		return err
	}
	out.Name = in.Name
	if err := Convert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(&in.InterfaceConfig, &out.InterfaceConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice is an autogenerated conversion function.
func Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(in *v1alpha2.AdditionalNetworkDevice, out *AdditionalNetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(in, out, s)
}

func autoConvert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in *DiskSize, out *v1alpha2.DiskSize, s conversion.Scope) error {
	out.Disk = in.Disk
	out.SizeGB = in.SizeGB
	return nil
}

// Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize is an autogenerated conversion function.
func Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in *DiskSize, out *v1alpha2.DiskSize, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in, out, s)
}

func autoConvert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in *v1alpha2.DiskSize, out *DiskSize, s conversion.Scope) error {
	out.Disk = in.Disk
	out.SizeGB = in.SizeGB
	return nil
}

// Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize is an autogenerated conversion function.
func Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in *v1alpha2.DiskSize, out *DiskSize, s conversion.Scope) error {
	return autoConvert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in, out, s)
}

func autoConvert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(in *IPAddress, out *v1alpha2.IPAddress, s conversion.Scope) error {
	out.IPV4 = in.IPV4
	out.IPV6 = in.IPV6
	return nil
}

// Convert_v1alpha1_IPAddress_To_v1alpha2_IPAddress is an autogenerated conversion function.
func Convert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(in *IPAddress, out *v1alpha2.IPAddress, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(in, out, s)
}

func autoConvert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(in *v1alpha2.IPAddress, out *IPAddress, s conversion.Scope) error {
	out.IPV4 = in.IPV4
	out.IPV6 = in.IPV6
	return nil
}

// Convert_v1alpha2_IPAddress_To_v1alpha1_IPAddress is an autogenerated conversion function.
func Convert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(in *v1alpha2.IPAddress, out *IPAddress, s conversion.Scope) error {
	return autoConvert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(in, out, s)
}

func autoConvert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(in *IPConfigSpec, out *v1alpha2.IPConfigSpec, s conversion.Scope) error {
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.Prefix = in.Prefix
	out.Gateway = in.Gateway
	out.Metric = (*uint32)(unsafe.Pointer(in.Metric))
	return nil
}

// Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(in *IPConfigSpec, out *v1alpha2.IPConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(in, out, s)
}

func autoConvert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(in *v1alpha2.IPConfigSpec, out *IPConfigSpec, s conversion.Scope) error {
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.Prefix = in.Prefix
	out.Gateway = in.Gateway
	out.Metric = (*uint32)(unsafe.Pointer(in.Metric))
	return nil
}

// Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec is an autogenerated conversion function.
func Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(in *v1alpha2.IPConfigSpec, out *IPConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(in *InterfaceConfig, out *v1alpha2.InterfaceConfig, s conversion.Scope) error {
	out.IPv4PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv4PoolRef))
	out.IPv6PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv6PoolRef))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	if err := Convert_v1alpha1_Routing_To_v1alpha2_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	out.LinkMTU = (v1alpha2.MTU)(unsafe.Pointer(in.LinkMTU))
	return nil
}

// Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig is an autogenerated conversion function.
func Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(in *InterfaceConfig, out *v1alpha2.InterfaceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(in, out, s)
}

func autoConvert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(in *v1alpha2.InterfaceConfig, out *InterfaceConfig, s conversion.Scope) error {
	out.IPv4PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv4PoolRef))
	out.IPv6PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv6PoolRef))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	if err := Convert_v1alpha2_Routing_To_v1alpha1_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	out.LinkMTU = (MTU)(unsafe.Pointer(in.LinkMTU))
	return nil
}

// Convert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig is an autogenerated conversion function.
func Convert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(in *v1alpha2.InterfaceConfig, out *InterfaceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(in, out, s)
}

func autoConvert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(in *MetadataSettings, out *v1alpha2.MetadataSettings, s conversion.Scope) error {
	out.ProviderIDInjection = in.ProviderIDInjection
	return nil
}

// Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings is an autogenerated conversion function.
func Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(in *MetadataSettings, out *v1alpha2.MetadataSettings, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(in, out, s)
}

func autoConvert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(in *v1alpha2.MetadataSettings, out *MetadataSettings, s conversion.Scope) error {
	out.ProviderIDInjection = in.ProviderIDInjection
	return nil
}

// Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings is an autogenerated conversion function.
func Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(in *v1alpha2.MetadataSettings, out *MetadataSettings, s conversion.Scope) error {
	return autoConvert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(in, out, s)
}

func autoConvert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in *NetworkDevice, out *v1alpha2.NetworkDevice, s conversion.Scope) error {
	out.Bridge = in.Bridge
	out.Model = (*string)(unsafe.Pointer(in.Model))
	out.MTU = (v1alpha2.MTU)(unsafe.Pointer(in.MTU))
	out.VLAN = (*uint16)(unsafe.Pointer(in.VLAN))
	return nil
}

// Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice is an autogenerated conversion function.
func Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in *NetworkDevice, out *v1alpha2.NetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in, out, s)
}

func autoConvert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(in *v1alpha2.NetworkDevice, out *NetworkDevice, s conversion.Scope) error {
	out.Bridge = in.Bridge
	out.Model = (*string)(unsafe.Pointer(in.Model))
	out.MTU = (MTU)(unsafe.Pointer(in.MTU))
	out.VLAN = (*uint16)(unsafe.Pointer(in.VLAN))
	return nil
}

// Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice is an autogenerated conversion function.
func Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(in *v1alpha2.NetworkDevice, out *NetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(in, out, s)
}

func autoConvert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in *NetworkSpec, out *v1alpha2.NetworkSpec, s conversion.Scope) error {
	out.Default = (*v1alpha2.NetworkDevice)(unsafe.Pointer(in.Default))
	out.AdditionalDevices = *(*[]v1alpha2.AdditionalNetworkDevice)(unsafe.Pointer(&in.AdditionalDevices))
	if err := Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(&in.VirtualNetworkDevices, &out.VirtualNetworkDevices, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in *NetworkSpec, out *v1alpha2.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in *v1alpha2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	out.Default = (*NetworkDevice)(unsafe.Pointer(in.Default))
	out.AdditionalDevices = *(*[]AdditionalNetworkDevice)(unsafe.Pointer(&in.AdditionalDevices))
	if err := Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(&in.VirtualNetworkDevices, &out.VirtualNetworkDevices, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in *v1alpha2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in *NetworkStatus, out *v1alpha2.NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in *NetworkStatus, out *v1alpha2.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in *v1alpha2.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in *v1alpha2.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in *NodeLocation, out *v1alpha2.NodeLocation, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Node = in.Node
	return nil
}

// Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in *NodeLocation, out *v1alpha2.NodeLocation, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in, out, s)
}

func autoConvert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in *v1alpha2.NodeLocation, out *NodeLocation, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Node = in.Node
	return nil
}

// Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation is an autogenerated conversion function.
func Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in *v1alpha2.NodeLocation, out *NodeLocation, s conversion.Scope) error {
	return autoConvert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in, out, s)
}

func autoConvert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in *NodeLocations, out *v1alpha2.NodeLocations, s conversion.Scope) error {
	out.ControlPlane = *(*[]v1alpha2.NodeLocation)(unsafe.Pointer(&in.ControlPlane))
	out.Workers = *(*[]v1alpha2.NodeLocation)(unsafe.Pointer(&in.Workers))
	return nil
}

// Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in *NodeLocations, out *v1alpha2.NodeLocations, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in, out, s)
}

func autoConvert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in *v1alpha2.NodeLocations, out *NodeLocations, s conversion.Scope) error {
	out.ControlPlane = *(*[]NodeLocation)(unsafe.Pointer(&in.ControlPlane))
	out.Workers = *(*[]NodeLocation)(unsafe.Pointer(&in.Workers))
	return nil
}

// Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations is an autogenerated conversion function.
func Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in *v1alpha2.NodeLocations, out *NodeLocations, s conversion.Scope) error {
	return autoConvert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in *ProxmoxCluster, out *v1alpha2.ProxmoxCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in *ProxmoxCluster, out *v1alpha2.ProxmoxCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in *v1alpha2.ProxmoxCluster, out *ProxmoxCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in *v1alpha2.ProxmoxCluster, out *ProxmoxCluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(in *ProxmoxClusterCloneSpec, out *v1alpha2.ProxmoxClusterCloneSpec, s conversion.Scope) error {
	out.ProxmoxMachineSpec = *(*map[string]v1alpha2.ProxmoxMachineSpec)(unsafe.Pointer(&in.ProxmoxMachineSpec))
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	out.VirtualIPNetworkInterface = in.VirtualIPNetworkInterface
	return nil
}

// Convert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(in *ProxmoxClusterCloneSpec, out *v1alpha2.ProxmoxClusterCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(in *v1alpha2.ProxmoxClusterCloneSpec, out *ProxmoxClusterCloneSpec, s conversion.Scope) error {
	out.ProxmoxMachineSpec = *(*map[string]ProxmoxMachineSpec)(unsafe.Pointer(&in.ProxmoxMachineSpec))
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	out.VirtualIPNetworkInterface = in.VirtualIPNetworkInterface
	return nil
}

// Convert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(in *v1alpha2.ProxmoxClusterCloneSpec, out *ProxmoxClusterCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in *ProxmoxClusterList, out *v1alpha2.ProxmoxClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in *ProxmoxClusterList, out *v1alpha2.ProxmoxClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in *v1alpha2.ProxmoxClusterList, out *ProxmoxClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in *v1alpha2.ProxmoxClusterList, out *ProxmoxClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in *ProxmoxClusterSpec, out *v1alpha2.ProxmoxClusterSpec, s conversion.Scope) error {
	out.ControlPlaneEndpoint = (*v1beta1.APIEndpoint)(unsafe.Pointer(in.ControlPlaneEndpoint))
	out.ExternalManagedControlPlane = in.ExternalManagedControlPlane
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	out.SchedulerHints = (*v1alpha2.SchedulerHints)(unsafe.Pointer(in.SchedulerHints))
	out.IPv4Config = (*v1alpha2.IPConfigSpec)(unsafe.Pointer(in.IPv4Config))
	out.IPv6Config = (*v1alpha2.IPConfigSpec)(unsafe.Pointer(in.IPv6Config))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.CloneSpec = (*v1alpha2.ProxmoxClusterCloneSpec)(unsafe.Pointer(in.CloneSpec))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in *ProxmoxClusterSpec, out *v1alpha2.ProxmoxClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(in *v1alpha2.ProxmoxClusterSpec, out *ProxmoxClusterSpec, s conversion.Scope) error {
	out.ControlPlaneEndpoint = (*v1beta1.APIEndpoint)(unsafe.Pointer(in.ControlPlaneEndpoint))
	// WARNING: in.Settings requires manual conversion: does not exist in peer-type
	out.ExternalManagedControlPlane = in.ExternalManagedControlPlane
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	out.SchedulerHints = (*SchedulerHints)(unsafe.Pointer(in.SchedulerHints))
	out.IPv4Config = (*IPConfigSpec)(unsafe.Pointer(in.IPv4Config))
	out.IPv6Config = (*IPConfigSpec)(unsafe.Pointer(in.IPv6Config))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	out.CloneSpec = (*ProxmoxClusterCloneSpec)(unsafe.Pointer(in.CloneSpec))
	out.CredentialsRef = (*v1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

func autoConvert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in *ProxmoxClusterStatus, out *v1alpha2.ProxmoxClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.InClusterIPPoolRef = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.InClusterIPPoolRef))
	out.NodeLocations = (*v1alpha2.NodeLocations)(unsafe.Pointer(in.NodeLocations))
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in *ProxmoxClusterStatus, out *v1alpha2.ProxmoxClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in *v1alpha2.ProxmoxClusterStatus, out *ProxmoxClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.InClusterIPPoolRef = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.InClusterIPPoolRef))
	out.NodeLocations = (*NodeLocations)(unsafe.Pointer(in.NodeLocations))
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in *v1alpha2.ProxmoxClusterStatus, out *ProxmoxClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(in *ProxmoxClusterTemplate, out *v1alpha2.ProxmoxClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(in *ProxmoxClusterTemplate, out *v1alpha2.ProxmoxClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(in *v1alpha2.ProxmoxClusterTemplate, out *ProxmoxClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(in *v1alpha2.ProxmoxClusterTemplate, out *ProxmoxClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(in *ProxmoxClusterTemplateList, out *v1alpha2.ProxmoxClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(in *ProxmoxClusterTemplateList, out *v1alpha2.ProxmoxClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(in *v1alpha2.ProxmoxClusterTemplateList, out *ProxmoxClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(in *v1alpha2.ProxmoxClusterTemplateList, out *ProxmoxClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(in *ProxmoxClusterTemplateResource, out *v1alpha2.ProxmoxClusterTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(in *ProxmoxClusterTemplateResource, out *v1alpha2.ProxmoxClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(in *v1alpha2.ProxmoxClusterTemplateResource, out *ProxmoxClusterTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(in *v1alpha2.ProxmoxClusterTemplateResource, out *ProxmoxClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(in *ProxmoxClusterTemplateSpec, out *v1alpha2.ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(in *ProxmoxClusterTemplateSpec, out *v1alpha2.ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(in *v1alpha2.ProxmoxClusterTemplateSpec, out *ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(in *v1alpha2.ProxmoxClusterTemplateSpec, out *ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in *ProxmoxMachine, out *v1alpha2.ProxmoxMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in *ProxmoxMachine, out *v1alpha2.ProxmoxMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in *v1alpha2.ProxmoxMachine, out *ProxmoxMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in *v1alpha2.ProxmoxMachine, out *ProxmoxMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(in *ProxmoxMachineChecks, out *v1alpha2.ProxmoxMachineChecks, s conversion.Scope) error {
	out.SkipCloudInitStatus = (*bool)(unsafe.Pointer(in.SkipCloudInitStatus))
	out.SkipQemuGuestAgent = (*bool)(unsafe.Pointer(in.SkipQemuGuestAgent))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(in *ProxmoxMachineChecks, out *v1alpha2.ProxmoxMachineChecks, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(in *v1alpha2.ProxmoxMachineChecks, out *ProxmoxMachineChecks, s conversion.Scope) error {
	out.SkipCloudInitStatus = (*bool)(unsafe.Pointer(in.SkipCloudInitStatus))
	out.SkipQemuGuestAgent = (*bool)(unsafe.Pointer(in.SkipQemuGuestAgent))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(in *v1alpha2.ProxmoxMachineChecks, out *ProxmoxMachineChecks, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in *ProxmoxMachineList, out *v1alpha2.ProxmoxMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.ProxmoxMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in *ProxmoxMachineList, out *v1alpha2.ProxmoxMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in *v1alpha2.ProxmoxMachineList, out *ProxmoxMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ProxmoxMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in *v1alpha2.ProxmoxMachineList, out *ProxmoxMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in *ProxmoxMachineSpec, out *v1alpha2.ProxmoxMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VirtualMachineID = (*int64)(unsafe.Pointer(in.VirtualMachineID))
	out.NumSockets = in.NumSockets
	out.NumCores = in.NumCores
	out.MemoryMiB = in.MemoryMiB
	out.Disks = (*v1alpha2.Storage)(unsafe.Pointer(in.Disks))
	out.Network = (*v1alpha2.NetworkSpec)(unsafe.Pointer(in.Network))
	out.VMIDRange = (*v1alpha2.VMIDRange)(unsafe.Pointer(in.VMIDRange))
	out.Checks = (*v1alpha2.ProxmoxMachineChecks)(unsafe.Pointer(in.Checks))
	out.MetadataSettings = (*v1alpha2.MetadataSettings)(unsafe.Pointer(in.MetadataSettings))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in *ProxmoxMachineSpec, out *v1alpha2.ProxmoxMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in *v1alpha2.ProxmoxMachineSpec, out *ProxmoxMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VirtualMachineID = (*int64)(unsafe.Pointer(in.VirtualMachineID))
	out.NumSockets = in.NumSockets
	out.NumCores = in.NumCores
	out.MemoryMiB = in.MemoryMiB
	out.Disks = (*Storage)(unsafe.Pointer(in.Disks))
	out.Network = (*NetworkSpec)(unsafe.Pointer(in.Network))
	out.VMIDRange = (*VMIDRange)(unsafe.Pointer(in.VMIDRange))
	out.Checks = (*ProxmoxMachineChecks)(unsafe.Pointer(in.Checks))
	out.MetadataSettings = (*MetadataSettings)(unsafe.Pointer(in.MetadataSettings))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in *v1alpha2.ProxmoxMachineSpec, out *ProxmoxMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in *ProxmoxMachineStatus, out *v1alpha2.ProxmoxMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.VMStatus = v1alpha2.VirtualMachineState(in.VMStatus)
	out.BootstrapDataProvided = (*bool)(unsafe.Pointer(in.BootstrapDataProvided))
	out.IPAddresses = *(*map[string]v1alpha2.IPAddress)(unsafe.Pointer(&in.IPAddresses))
	out.Network = *(*[]v1alpha2.NetworkStatus)(unsafe.Pointer(&in.Network))
	out.ProxmoxNode = (*string)(unsafe.Pointer(in.ProxmoxNode))
	out.TaskRef = (*string)(unsafe.Pointer(in.TaskRef))
	out.RetryAfter = in.RetryAfter
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in *ProxmoxMachineStatus, out *v1alpha2.ProxmoxMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in *v1alpha2.ProxmoxMachineStatus, out *ProxmoxMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.VMStatus = VirtualMachineState(in.VMStatus)
	out.BootstrapDataProvided = (*bool)(unsafe.Pointer(in.BootstrapDataProvided))
	out.IPAddresses = *(*map[string]IPAddress)(unsafe.Pointer(&in.IPAddresses))
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	out.ProxmoxNode = (*string)(unsafe.Pointer(in.ProxmoxNode))
	out.TaskRef = (*string)(unsafe.Pointer(in.TaskRef))
	out.RetryAfter = in.RetryAfter
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in *v1alpha2.ProxmoxMachineStatus, out *ProxmoxMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in *ProxmoxMachineTemplate, out *v1alpha2.ProxmoxMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in *ProxmoxMachineTemplate, out *v1alpha2.ProxmoxMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in *v1alpha2.ProxmoxMachineTemplate, out *ProxmoxMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in *v1alpha2.ProxmoxMachineTemplate, out *ProxmoxMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in *ProxmoxMachineTemplateList, out *v1alpha2.ProxmoxMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha2.ProxmoxMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in *ProxmoxMachineTemplateList, out *v1alpha2.ProxmoxMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in *v1alpha2.ProxmoxMachineTemplateList, out *ProxmoxMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ProxmoxMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in *v1alpha2.ProxmoxMachineTemplateList, out *ProxmoxMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in *ProxmoxMachineTemplateResource, out *v1alpha2.ProxmoxMachineTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in *ProxmoxMachineTemplateResource, out *v1alpha2.ProxmoxMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in *v1alpha2.ProxmoxMachineTemplateResource, out *ProxmoxMachineTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in *v1alpha2.ProxmoxMachineTemplateResource, out *ProxmoxMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in *ProxmoxMachineTemplateSpec, out *v1alpha2.ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in *ProxmoxMachineTemplateSpec, out *v1alpha2.ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in *v1alpha2.ProxmoxMachineTemplateSpec, out *ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in *v1alpha2.ProxmoxMachineTemplateSpec, out *ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(in *RouteSpec, out *v1alpha2.RouteSpec, s conversion.Scope) error {
	out.To = in.To
	out.Via = in.Via
	out.Metric = in.Metric
	out.Table = in.Table
	return nil
}

// Convert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec is an autogenerated conversion function.
func Convert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(in *RouteSpec, out *v1alpha2.RouteSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(in, out, s)
}

func autoConvert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(in *v1alpha2.RouteSpec, out *RouteSpec, s conversion.Scope) error {
	out.To = in.To
	out.Via = in.Via
	out.Metric = in.Metric
	out.Table = in.Table
	return nil
}

// Convert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec is an autogenerated conversion function.
func Convert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(in *v1alpha2.RouteSpec, out *RouteSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(in, out, s)
}

func autoConvert_v1alpha1_Routing_To_v1alpha2_Routing(in *Routing, out *v1alpha2.Routing, s conversion.Scope) error {
	out.Routes = *(*[]v1alpha2.RouteSpec)(unsafe.Pointer(&in.Routes))
	out.RoutingPolicy = *(*[]v1alpha2.RoutingPolicySpec)(unsafe.Pointer(&in.RoutingPolicy))
	return nil
}

// Convert_v1alpha1_Routing_To_v1alpha2_Routing is an autogenerated conversion function.
func Convert_v1alpha1_Routing_To_v1alpha2_Routing(in *Routing, out *v1alpha2.Routing, s conversion.Scope) error {
	return autoConvert_v1alpha1_Routing_To_v1alpha2_Routing(in, out, s)
}

func autoConvert_v1alpha2_Routing_To_v1alpha1_Routing(in *v1alpha2.Routing, out *Routing, s conversion.Scope) error {
	out.Routes = *(*[]RouteSpec)(unsafe.Pointer(&in.Routes))
	out.RoutingPolicy = *(*[]RoutingPolicySpec)(unsafe.Pointer(&in.RoutingPolicy))
	return nil
}

// Convert_v1alpha2_Routing_To_v1alpha1_Routing is an autogenerated conversion function.
func Convert_v1alpha2_Routing_To_v1alpha1_Routing(in *v1alpha2.Routing, out *Routing, s conversion.Scope) error {
	return autoConvert_v1alpha2_Routing_To_v1alpha1_Routing(in, out, s)
}

func autoConvert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(in *RoutingPolicySpec, out *v1alpha2.RoutingPolicySpec, s conversion.Scope) error {
	out.To = in.To
	out.From = in.From
	out.Table = (*uint32)(unsafe.Pointer(in.Table))
	out.Priority = in.Priority
	return nil
}

// Convert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec is an autogenerated conversion function.
func Convert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(in *RoutingPolicySpec, out *v1alpha2.RoutingPolicySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(in, out, s)
}

func autoConvert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(in *v1alpha2.RoutingPolicySpec, out *RoutingPolicySpec, s conversion.Scope) error {
	out.To = in.To
	out.From = in.From
	out.Table = (*uint32)(unsafe.Pointer(in.Table))
	out.Priority = in.Priority
	return nil
}

// Convert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec is an autogenerated conversion function.
func Convert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(in *v1alpha2.RoutingPolicySpec, out *RoutingPolicySpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(in, out, s)
}

func autoConvert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(in *SchedulerHints, out *v1alpha2.SchedulerHints, s conversion.Scope) error {
	out.MemoryAdjustment = (*uint64)(unsafe.Pointer(in.MemoryAdjustment))
	return nil
}

// Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints is an autogenerated conversion function.
func Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(in *SchedulerHints, out *v1alpha2.SchedulerHints, s conversion.Scope) error {
	return autoConvert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(in, out, s)
}

func autoConvert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(in *v1alpha2.SchedulerHints, out *SchedulerHints, s conversion.Scope) error {
	out.MemoryAdjustment = (*uint64)(unsafe.Pointer(in.MemoryAdjustment))
	return nil
}

// Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints is an autogenerated conversion function.
func Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(in *v1alpha2.SchedulerHints, out *SchedulerHints, s conversion.Scope) error {
	return autoConvert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_v1alpha2_Storage(in *Storage, out *v1alpha2.Storage, s conversion.Scope) error {
	out.BootVolume = (*v1alpha2.DiskSize)(unsafe.Pointer(in.BootVolume))
	return nil
}

// Convert_v1alpha1_Storage_To_v1alpha2_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_v1alpha2_Storage(in *Storage, out *v1alpha2.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_v1alpha2_Storage(in, out, s)
}

func autoConvert_v1alpha2_Storage_To_v1alpha1_Storage(in *v1alpha2.Storage, out *Storage, s conversion.Scope) error {
	out.BootVolume = (*DiskSize)(unsafe.Pointer(in.BootVolume))
	return nil
}

// Convert_v1alpha2_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_v1alpha2_Storage_To_v1alpha1_Storage(in *v1alpha2.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_v1alpha2_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(in *VMIDRange, out *v1alpha2.VMIDRange, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	return nil
}

// Convert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange is an autogenerated conversion function.
func Convert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(in *VMIDRange, out *v1alpha2.VMIDRange, s conversion.Scope) error {
	return autoConvert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(in, out, s)
}

func autoConvert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(in *v1alpha2.VMIDRange, out *VMIDRange, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	return nil
}

// Convert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange is an autogenerated conversion function.
func Convert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(in *v1alpha2.VMIDRange, out *VMIDRange, s conversion.Scope) error {
	return autoConvert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(in, out, s)
}

func autoConvert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(in *VRFDevice, out *v1alpha2.VRFDevice, s conversion.Scope) error {
	out.Interfaces = *(*[]string)(unsafe.Pointer(&in.Interfaces))
	out.Name = in.Name
	out.Table = in.Table
	if err := Convert_v1alpha1_Routing_To_v1alpha2_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice is an autogenerated conversion function.
func Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(in *VRFDevice, out *v1alpha2.VRFDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(in, out, s)
}

func autoConvert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(in *v1alpha2.VRFDevice, out *VRFDevice, s conversion.Scope) error {
	out.Interfaces = *(*[]string)(unsafe.Pointer(&in.Interfaces))
	out.Name = in.Name
	out.Table = in.Table
	if err := Convert_v1alpha2_Routing_To_v1alpha1_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice is an autogenerated conversion function.
func Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(in *v1alpha2.VRFDevice, out *VRFDevice, s conversion.Scope) error {
	return autoConvert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in *VirtualMachine, out *v1alpha2.VirtualMachine, s conversion.Scope) error {
	out.Node = in.Node
	out.Name = in.Name
	out.VMID = in.VMID
	out.State = v1alpha2.VirtualMachineState(in.State)
	out.Network = *(*[]v1alpha2.NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in *VirtualMachine, out *v1alpha2.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in *v1alpha2.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.Node = in.Node
	out.Name = in.Name
	out.VMID = in.VMID
	out.State = VirtualMachineState(in.State)
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in *v1alpha2.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1alpha2.VirtualMachineCloneSpec, s conversion.Scope) error {
	out.SourceNode = in.SourceNode
	out.TemplateID = (*int32)(unsafe.Pointer(in.TemplateID))
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.Format = (*v1alpha2.TargetFileStorageFormat)(unsafe.Pointer(in.Format))
	out.Full = (*bool)(unsafe.Pointer(in.Full))
	out.Pool = (*string)(unsafe.Pointer(in.Pool))
	out.SnapName = (*string)(unsafe.Pointer(in.SnapName))
	out.Storage = (*string)(unsafe.Pointer(in.Storage))
	out.Target = (*string)(unsafe.Pointer(in.Target))
	return nil
}

// Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1alpha2.VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in *v1alpha2.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	out.SourceNode = in.SourceNode
	out.TemplateID = (*int32)(unsafe.Pointer(in.TemplateID))
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.Format = (*TargetFileStorageFormat)(unsafe.Pointer(in.Format))
	out.Full = (*bool)(unsafe.Pointer(in.Full))
	out.Pool = (*string)(unsafe.Pointer(in.Pool))
	out.SnapName = (*string)(unsafe.Pointer(in.SnapName))
	out.Storage = (*string)(unsafe.Pointer(in.Storage))
	out.Target = (*string)(unsafe.Pointer(in.Target))
	return nil
}

// Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in *v1alpha2.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(in *VirtualNetworkDevices, out *v1alpha2.VirtualNetworkDevices, s conversion.Scope) error {
	out.VRFs = *(*[]v1alpha2.VRFDevice)(unsafe.Pointer(&in.VRFs))
	return nil
}

// Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices is an autogenerated conversion function.
func Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(in *VirtualNetworkDevices, out *v1alpha2.VirtualNetworkDevices, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(in, out, s)
}

func autoConvert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(in *v1alpha2.VirtualNetworkDevices, out *VirtualNetworkDevices, s conversion.Scope) error {
	out.VRFs = *(*[]VRFDevice)(unsafe.Pointer(&in.VRFs))
	return nil
}

// Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices is an autogenerated conversion function.
func Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(in *v1alpha2.VirtualNetworkDevices, out *VirtualNetworkDevices, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(in, out, s)
}
